---
- name: Run ansbile on a Docker container
  hosts: all
  become: yes    
  become_user: root
  tasks:
    - name: Install openjdk
      apt:
        name: openjdk-8-jdk
        install_recommends: no
